# Copyright (c) 2016-2022 Martin Donath <martin.donath@squidfunk.com>

# Project information
site_name: Home
site_url: https://github.com/fralfaro/soche_cursos
site_author: Francisco Alfaro
site_description: Ciclo de Minicursos - SOCHE

# Repository
repo_name: fralfaro/soche_cursos
repo_url: https://github.com/fralfaro/soche_cursos
edit_uri: ''



# Markdown extensions
markdown_extensions:
  - attr_list
  - admonition
  - md_in_html
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tasklist
  - pymdownx.tabbed



# Extra javascript
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

# Theme
theme:
  name: material
  language: es
  logo: images/logo.bmp
  features:
    - navigation.instant
    - navigation.top
    - content.code.annotate
    - search.suggest
    - search.highlight
  palette:
    # Light mode
    - media: '(prefers-color-scheme: light)'
      scheme: default
      primary: blue grey
      accent: light blue
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode

    # Dark mode
    - media: '(prefers-color-scheme: dark)'
      scheme: slate
      primary: blue grey
      accent: light blue
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

# Customization
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/fralfaro
    - icon: fontawesome/brands/gitlab
      link: https://gitlab.com/fralfaro
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/faam/
    - icon: fontawesome/brands/kaggle
      link: https://www.kaggle.com/faamds
    - icon: fontawesome/brands/medium
      link: https://medium.com/@fralfaro

# Plugins
plugins:
  - mkdocs-jupyter:
      kernel_name: python3
  - search


# TOC
nav:
    - Home: index.md
    - 2020:
        - Visualización de datos en RStudio:
            - 2020/01_visualizacion/intro.md
            - docs/2020/01_visualizacion/codigo_r.ipynb
        - docs/2020/02_analisis_sobrevivencia/codigo_r.ipynb
        - docs/2020/03_rmarkdown/codigo_r.ipynb
    - 2022:
        - docs/2020/01_visualizacion/codigo_r.ipynb
        - docs/2020/02_analisis_sobrevivencia/codigo_r.ipynb
        - docs/2020/03_rmarkdown/codigo_r.ipynb

